{{- if .Values.ingress.enabled -}}
{{- $defaultPort := (include "instant-chart.firstServicePort" . | fromYaml).port -}}
{{- if eq (include "common.ingress.supportsIngressClassname" .) "false" }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: {{ template "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "instant-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if eq (include "common.ingress.supportsIngressClassname" .) "true" }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.rules }}
  {{- if not .paths }}
  {{- $_ := set . "paths" (list (dict "path" "/" "pathType" "ImplementationSpecific" "servicePort" $defaultPort)) -}}
  {{- end }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        {{- if eq (include "common.ingress.supportsPathType" $) "true" }}
        pathType: {{ default "ImplementationSpecific" .pathType }}
        {{- end }}
        backend:
          {{- include "common.ingress.backend" (dict
            "serviceName" (default $.Release.Name .serviceName)
            "servicePort" (default $defaultPort .servicePort)
            "context" $
          ) | nindent 10 }}
      {{- end }}
  {{- end }}
{{- end }}
