{{- if .Values.service.enabled -}}
{{- $container := (include "instant-chart.firstContainer" . | fromYaml).container -}}
{{- $defaultPort := (include "instant-chart.firstContainerPort" $container | fromYaml).port -}}
{{- $ports := .Values.service.ports | default (list (dict "port" $defaultPort)) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "instant-chart.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "instant-chart.matchLabels" . | nindent 4 }}
  ports:
  {{- range $index, $port := $ports }}
  - name: {{ $port.name | default (printf "port-%d" $index) }}
    port: {{ $port.port | default $defaultPort }}
    targetPort: {{ $port.targetPort | default $port.port | default $defaultPort }}
    {{- $extra := omit $port  "name" "port" "targetPort" "protocol" -}}
    {{- if $extra }}
    {{- toYaml $extra | nindent 4 }}
    {{- end }}
    protocol: {{ $port.protocol | default "TCP" }}
  {{- end }}
  {{- toYaml (omit .Values.service  "enabled" "selector" "annotations" "labels" "ports") | nindent 2 }}
{{- end -}}
