{{- $kind := include "instant-chart.resource.kind" . -}}

{{- if eq $kind "StatefulSet" -}}
{{- if .Values.containers }}
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: {{ $kind }}
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "instant-chart.labels" . | nindent 4 }}
  annotations:
    checksum/configmaps: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.statefulSet.ordinals }}
  ordinals:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.statefulSet.persistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.statefulSet.podManagementPolicy }}
  podManagementPolicy: {{ .Values.statefulSet.podManagementPolicy }}
  {{- end }}
  replicas: {{ .Values.replicas }}
  serviceName: {{ .Values.statefulSet.serviceName | default "" }}
  selector:
    matchLabels:
      {{- include "instant-chart.matchLabels" . | nindent 6 }}
  template:
    {{- include "instant-chart.podTemplate" . | nindent 4 }}
  updateStrategy:
    {{- include "instant-chart.resource.updateStrategy" . | nindent 4 }}
  {{- with .Values.statefulSet.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}
